### ISSUE TITLE
file:// only ?

### ISSUE THREAD

**Issue by patatetom** [painyeph/GitLabMarkdownViewer#4]
hi,
GitLabMarkdownViewer only renders local files ?
regards.

**Comment by painyeph** [comment]
@patatetom Yes, but you can modify `"matches": ["file:///*.md", "file:///*.markdown"],` in manifest.json.

**Comment by patatetom** [comment]
I hope you will modify your signed `manifest.json` because I have to use your nice extension as a temporary extension if I modify the file.
regards.

**Comment by sergeevabc** [comment]
@painyeph, you’d better mention this on frontpage, because I expected it to render ```*.md``` globally.
