### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by fergiemcdowall** [painyeph/GitLabMarkdownViewer#5]
Trying to get this plugin to work on firefox in Ubuntu 18. It installs OK, but doesn't seem to render any .md files that I open. Is there something you have to do to get it to work?

Tips?

**Comment by painyeph** [comment]
@fergiemcdowall You may need to modify the way OS handle MIME types. See https://superuser.com/q/696361

**Comment by fergiemcdowall** [comment]
@painyeph thanks! Yes the [first answer on that thread](https://superuser.com/a/1175837/297776) got GitLab Markdown Viewer working for me
